
// ActiveOberon Compiler, a native ARM v8 & X86-64 compiler / linker / builder utility.
// Written by Richard Magnor Stenbro. Licensed under GPL v3
// Arm64 Assembler instruction-set module for compiling and linking of projects written in ActiveOberon language


use crate::arm64_instruction_set::NeonEncoding::EncodeNEONVFP2Reg;

/// Conditional part of an opcode.
pub enum Conditional {
    ConditionEQ = 0,
    ConditionNE = 1,
    ConditionCS = 2,
    ConditionCC = 3,
    ConditionMI = 4,
    ConditionPL = 5,
    ConditionVS = 6,
    ConditionVC = 7,
    ConditionHI = 8,
    ConditionLS = 9,
    ConditionGE = 10,
    ConditionLT = 11,
    ConditionGT = 12,
    ConditionLE = 13,
    ConditionAL = 14,
    ConditionNV = 15,
}

impl Conditional {
    pub const ConditionHS: Conditional = Conditional::ConditionCS;
    pub const ConditionLO: Conditional = Conditional::ConditionCC;
    pub const Unconditional: Conditional = Conditional::ConditionAL;
}

pub enum IndexFlags {
    Increment = 0,
    Decrement = 1,
    PostIndexed = 2,
    PreIndexed = 3
}

/// ARM64 Opcodes supported by inline assembler
pub enum Opcodes {
    OpAdc = 0,
    OpAdd = 1,
    OpAnd = 2,
    OpB = 3,
    OpBic = 4,
    OpBkpt = 5,
    OpBl = 6,
    OpBlx = 7,
    OpBx = 8,
    OpCdp = 9,
    OpCdp2 = 10,
    OpClz = 11,
    OpCmn = 12,
    OpCmp = 13,
    OpEor = 14,
    OpFabsd = 15,
    OpFabss = 16,
    OpFaddd = 17,
    OpFadds = 18,
    OpFcmpd = 19,
    OpFcmped = 20,
    OpFcmpes = 21,
    OpFcmpezd = 22,
    OpFcmpezs = 23,
    OpFcmps = 24,
    OpFcmpzd = 25,
    OpFcmpzs = 26,
    OpFcpyd = 27,
    OpFcpys = 28,
    OpFcvtds = 29,
    OpFcvtsd = 30,
    OpFdivd = 31,
    OpFdivs = 32,
    OpFldd = 33,
    OpFldmiad = 34,
    OpFldmias = 35,
    OpFldmiax = 36,
    OpFldmdbd = 37,
    OpFldmdbs = 38,
    OpFldmdbx = 39,
    OpFlds = 40,
    OpFmacd = 41,
    OpFmacs = 42,
    OpFmdhr = 43,
    OpFmdlr = 44,
    OpFmrdh = 45,
    OpFmrdl = 46,
    OpFmrs = 47,
    OpFmrx = 48,
    OpFmscd = 49,
    OpFmscs = 50,
    OpFmsr = 51,
    OpFmstat = 52,
    OpFmuld = 53,
    OpFmuls = 54,
    OpFmxr = 55,
    OpFnegd = 56,
    OpFnegs = 57,
    OpFnmacd = 58,
    OpFnmacs = 59,
    OpFnmscd = 60,
    OpFnmscs = 61,
    OpFnmuld = 62,
    OpFnmuls = 63,
    OpFsitod = 64,
    OpFsitos = 65,
    OpFsqrtd = 66,
    OpFsqrts = 67,
    OpFstd = 68,
    OpFstmiad = 69,
    OpFstmias = 70,
    OpFstmiax = 71,
    OpFstmdbd = 72,
    OpFstmdbs = 73,
    OpFstmdbx = 74,
    OpFsts = 75,
    OpFsubd = 76,
    OpFsubs = 77,
    OpFtosid = 78,
    OpFtosizd = 79,
    OpFtosis = 80,
    OpFtosizs = 81,
    OpFtouid = 82,
    OpFtouizd = 83,
    OpFtouis = 84,
    OpFtouizs = 85,
    OpFuitod = 86,
    OpFuitos = 87,
    OpLdc = 88,
    OpLdc2 = 89,
    OpLdm = 90,
    OpLdr = 91,
    OpMcr = 92,
    OpMcr2 = 93,
    OpMcrr = 94,
    OpMla = 95,
    OpMov = 96,
    OpMrc = 97,
    OpMrc2 = 98,
    OpMrrc = 99,
    OpMrs = 100,
    OpMsr = 101,
    OpMul = 102,
    OpMvn = 103,
    OpOrr = 104,
    OpPld = 105,
    OpQadd = 106,
    OpQdadd = 107,
    OpQdsub = 108,
    OpQsub = 109,
    OpRsb = 110,
    OpRsc = 111,
    OpSbc = 112,
    OpSmlabb = 113,
    OpSmlabt = 114,
    OpSmlal = 115,
    OpSmlatb = 116,
    OpSmlatt = 117,
    OpSmlalbb = 118,
    OpSmlalbt = 119,
    OpSmlaltb = 120,
    OpSmlaltt = 121,
    OpSmlawb = 122,
    OpSmlawt = 123,
    OpSmulbb = 124,
    OpSmulbt = 125,
    OpSmultb = 126,
    OpSmultt = 127,
    OpSmulwb = 128,
    OpSmulwt = 129,
    OpSmull = 130,
    OpStc = 131,
    OpStc2 = 132,
    OpStm = 133,
    OpStr = 134,
    OpSub = 135,
    OpSwi = 136,
    OpSwp = 137,
    OpTeq = 138,
    OpTst = 139,
    OpUmlal = 140,
    OpUmull = 141,
    OpIsb = 142,
    OpVadd = 143,
    OpVaddl = 144,
    OpVaddw = 145,
    OpVmul = 146,
    OpVmull = 147,
    OpVmsr = 148,
    OpVmrs = 149,
    OpVldr = 150,
    OpVstr = 151,
    OpVdiv = 152,
    OpVmla = 153,
    OpVmls = 154,
    OpVmin = 155,
    OpVmax = 156,
    OpVsub = 157,
    OpVabs = 158,
    OpVabd = 159,
    OpLsl = 160,
    OpLsr = 161,
    OpVld1 = 162,
    OpVst1 = 163,
    OpVpadd = 164,
    OpVmov = 165,
    OpSev = 166,
    OpDsb = 167,
    OpLdrex = 168,
    OpStrex = 169,
    OpAdr = 170,
    OpLdrexb = 171,
    OpStrexb = 172,
    OpDmb = 173,
    OpClrex = 174,
    OpRev = 175,
    OpRev16 = 176,
    OpUxth = 177,
    OpWfe = 178,
    OpWfi = 179,
    OpMovw = 180,
    OpUdf = 181,
}

pub enum Flags {
    FlagB = 0,
    FlagBT = 1,
    FlagD = 2,
    FlagDA = 3,
    FlagDB = 4,
    FlagH = 5,
    FlagIA = 6,
    FlagIB = 7,
    FlagL = 8,
    FlagS = 9,
    FlagSB = 10,
    FlagSH = 11,
    FlagT = 12,
    FlagNEON8bits = 13,
    FlagNEON16bits = 14,
    FlagNEON32bits = 15,
    FlagNEON64bits = 16,
    FlagNEONInt = 17,
    FlagNEONSigned = 18,
    FlagNEONUnsigned = 19,
    FlagNEONFloat = 20,
    FlagNEONPoly = 21,
    FlagNEONUndef = 22,
    FlagCondition = 23,
    FlagUserMode = 24,
    FlagBaseRegisterUpdate = 25
}

pub enum Encoding {
    EncodingR16= 0,
    EncodingR12= 1,
    EncodingR8= 2,
    EncodingR0= 3,
    EncodingAddressingMode1= 4,
    EncodingAddressingMode2= 5,
    EncodingAddressingMode3= 6,
    EncodingAddressingMode5= 7,
    EncodingCoprocessor= 8,
    EncodingCR0= 9,
    EncodingCR12= 10,
    EncodingCR16= 11,
    EncodingOpcode20= 12,
    EncodingOpcode21= 13,
    EncodingOpcode5= 14,
    EncodingOpcode4= 15,
    EncodingSignedImm24= 16,
    EncodingImm24= 17,
    EncodingImm16= 18,
    EncodingRotImm8= 19,
    EncodingRegisterList= 20,
    EncodingPSR= 21,
    EncodingFields= 22,
    EncodingDR0= 23,
    EncodingDR12= 24,
    EncodingDR16= 25,
    EncodingFR0= 26,
    EncodingFR12= 27,
    EncodingFR16= 28,
    EncodingDRegisterList= 29,
    EncodingFRegisterList= 30,
    EncodingAddressingMode5V= 31,
    EncodingNEONQd = 32,
    EncodingNEONQn = 33,
    EncodingNEONQm = 34,
    EncodingNEONDd = 35,
    EncodingNEONDn = 36,
    EncodingNEONDm = 37,
    EncodingNEONSd = 38,
    EncodingNEONSn = 39,
    EncodingNEONSm = 40,
    EncodingNEONImmAndSize = 41,
    EncodingNEON8bitImm = 42,
    EncodingNEON3bitImm = 43,
    EncodingNEONQorDd = 44,
    EncodingNEONQorDn = 45,
    EncodingNEONQorDm = 46,
    EncodingNEONDorSd = 47,
    EncodingNEONDorSn = 48,
    EncodingNEONDorSm = 49,
    EncodingNEONDRegList = 50,
    EncodingNEONSysReg = 51,
    EncodingNEONSigned8bitImm = 52,
    EncodingImm7to11 = 53,
    EncodingImm12a0imm4a16 = 54
}

pub enum NeonEncoding {
    EncodeNEON3RegSame = 0,
    EncodeNEON3RegLong = 1,
    EncodeNEON3RegNarrow = 2,
    EncodeNEON3RegWide = 3,
    EncodeNEON2RegScalar = 4,
    EncodeNEON2RegScalarLong = 5,
    EncodeNEON2RegShift = 6,
    EncodeNEON2RegShiftNarrow = 7,
    EncodeNEON2RegShiftLong = 8,
    EncodeNEON2RegMisc = 9,
    EncodeNEON2RegMiscNarrow = 10,
    EncodeNEON2RegMiscLong = 11,
    EncodeNEONVFP = 12,
    EncodeNEONVFP2Reg = 13,
    EncodeNEONVFP1Reg = 14
}

pub enum ModFlags {
    ModeImmediate = 0,
    ModeRegister = 1,
    ModeMemory = 2,
    ModeOpcode = 3,
    ModeCoprocessor = 4,
    ModeRegisterList = 5,
    ModeRegisterWithFields = 6,
    ModeOption = 7
}

pub enum Register {
    R0 = 0,
    R1 = 1,
    R2 = 2,
    R3 = 3,
    R4 = 4,
    R5 = 5,
    R6 = 6,
    R7 = 7,
    R8 = 8,
    R9 = 9,
    R10 = 10,
    R11 = 11,
    R12 = 12,
    R13 = 13,
    R14 = 14,
    R15 = 15,
    CR0 = 16,
    CR1 = 17,
    CR2 = 18,
    CR3 = 19,
    CR4 = 20,
    CR5 = 21,
    CR6 = 22,
    CR7 = 23,
    CR8 = 24,
    CR9 = 25,
    CR10 = 26,
    CR11 = 27,
    CR12 = 28,
    CR13 = 29,
    CR14 = 30,
    CR15 = 31,
    DR0 = 32,
    DR1 = 33,
    DR2 = 34,
    DR3 = 35,
    DR4 = 36,
    DR5 = 37,
    DR6 = 38,
    DR7 = 39,
    DR8 = 40,
    DR9 = 41,
    DR10 = 42,
    DR11 = 43,
    DR12 = 44,
    DR13 = 45,
    DR14 = 46,
    DR15 = 47,
    DR16 = 48,
    DR17 = 49,
    DR18 = 50,
    DR19 = 51,
    DR20 = 52,
    DR21 = 53,
    DR22 = 54,
    DR23 = 55,
    DR24 = 56,
    DR25 = 57,
    DR26 = 58,
    DR27 = 59,
    DR28 = 60,
    DR29 = 61,
    DR30 = 62,
    DR31 = 63,
    SR0 = 64,
    SR1 = 65,
    SR2 = 66,
    SR3 = 67,
    SR4 = 68,
    SR5 = 69,
    SR6 = 70,
    SR7 = 71,
    SR8 = 72,
    SR9 = 73,
    SR10 = 74,
    SR11 = 75,
    SR12 = 76,
    SR13 = 77,
    SR14 = 78,
    SR15 = 79,
    CPSR = 80,
    SPSR = 81,
    SR16 = 82,
    SR17 = 83,
    SR18 = 84,
    SR19 = 85,
    SR20 = 86,
    SR21 = 87,
    SR22 = 88,
    SR23 = 89,
    SR24 = 90,
    SR25 = 91,
    SR26 = 92,
    SR27 = 93,
    SR28 = 94,
    SR29 = 95,
    SR30 = 96,
    SR31 = 97,
    QR0 = 98,
    QR1 = 99,
    QR2 = 100,
    QR3 = 101,
    QR4 = 102,
    QR5 = 103,
    QR6 = 104,
    QR7 = 105,
    QR8 = 106,
    QR9 = 107,
    QR10 = 108,
    QR11 = 109,
    QR12 = 110,
    QE13 = 111,
    QR14 = 112,
    QR15 = 113,
    FPSID = 114,
    FPSCR = 115,
    FPEXC = 116
}

impl Register {
    pub const PC: Register = Register::R15;
    pub const LR: Register = Register::R14;
    pub const SP: Register = Register::R13;
    pub const FP: Register = Register::R11;
    pub const AP: Register = Register::R12;
    pub const RESHI: Register = Register::R1;
    pub const RES: Register = Register::R0;
    pub const RESFS: Register = Register::SR0;
    pub const RESFD: Register = Register::DR0;
}

pub enum Shifts {
    shiftLSL = 0,
    shiftLSR = 1,
    shiftASR = 2,
    shiftROR = 3,
    shiftRRX = 4,
    NumberShifts = 5
}

pub enum CoProsessor {
    CP0 = 0,
    CP1 = 1,
    CP2 = 2,
    CP3 = 3,
    CP4 = 4,
    CP5 = 5,
    CP6 = 6,
    CP7 = 7,
    CP8 = 8,
    CP9 = 9,
    CP10 = 10,
    CP11 = 11,
    CP12 = 12,
    CP13 = 13,
    CP14 = 14,
    CP15 = 15
}

pub enum Field {
    FieldC = 0,
    FieldX = 1,
    FieldS = 2,
    FieldF = 3
}


const BITS_12: u32 = 4096;
const BITS_10: u32 = 1024;
const BITS_7: u32 = 128;
const BITS_5: u32 = 32;

// Mnemonics used in ARM64 assembler code

#[derive()]
pub struct Mnemonic {
    name: &'static str,
    number: Opcodes,
    first_instruction_format: Encoding,
    last_instruction_format: Encoding
}

const MNEMONIC_ARM64: [Mnemonic; 181] = [
    Mnemonic { name: "ADC", number: Opcodes::OpAdc, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "ADD", number: Opcodes::OpAdd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "B", number: Opcodes::OpB, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "BIC", number: Opcodes::OpBic, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "BKPT", number: Opcodes::OpBkpt, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "BL", number: Opcodes::OpBl, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "BLX", number: Opcodes::OpBlx, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "BX", number: Opcodes::OpBx, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "CDP", number: Opcodes::OpCdp, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "CDP2", number: Opcodes::OpCdp, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "CLZ", number: Opcodes::OpClz, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "CMN", number: Opcodes::OpCmn, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "CMP", number: Opcodes::OpCmp, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "EOR", number: Opcodes::OpEor, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FABSD", number: Opcodes::OpFabsd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FABSS", number: Opcodes::OpFabss, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FADDD", number: Opcodes::OpFaddd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FADDS", number: Opcodes::OpFadds, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FCMPD", number: Opcodes::OpFcmpd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FCMPED", number: Opcodes::OpFcmped, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FCMPES", number: Opcodes::OpFcmpes, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FCMPEZD", number: Opcodes::OpFcmpezd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FCMPEZS", number: Opcodes::OpFcmpezs, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FCMPS", number: Opcodes::OpFcmps, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FCMPZD", number: Opcodes::OpFcmpzd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FCMPZS", number: Opcodes::OpFcmpzs, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FCPYD", number: Opcodes::OpFcpyd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FCPYS", number: Opcodes::OpFcpys, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FCVTDS", number: Opcodes::OpFcvtds, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FCVTSD", number: Opcodes::OpFcvtsd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FDIVD", number: Opcodes::OpFdivd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FDIVS", number: Opcodes::OpFdivs, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FLDD", number: Opcodes::OpFldd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FLDMIAD", number: Opcodes::OpFldmiad, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FLDMIAS", number: Opcodes::OpFldmias, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FLDMIAX", number: Opcodes::OpFldmiax, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FLDMDBD", number: Opcodes::OpFldmdbd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FLDMDBS", number: Opcodes::OpFldmdbs, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FLDMDBX", number: Opcodes::OpFldmdbx, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FLDS", number: Opcodes::OpFlds, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FMACD", number: Opcodes::OpFmacd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FMACS", number: Opcodes::OpFmacs, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FMDHR", number: Opcodes::OpFmdhr, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FMDLR", number: Opcodes::OpFmdlr, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FMRDH", number: Opcodes::OpFmrdh, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FMRDL", number: Opcodes::OpFmrdl, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FMRS", number: Opcodes::OpFmrs, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FMRX", number: Opcodes::OpFmrx, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FMSCD", number: Opcodes::OpFmscd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FMSCS", number: Opcodes::OpFmscs, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FMSR", number: Opcodes::OpFmsr, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FMSTAT", number: Opcodes::OpFmstat, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FMULD", number: Opcodes::OpFmuld, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FMULS", number: Opcodes::OpFmuls, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FMXR", number: Opcodes::OpFmxr, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FNEGD", number: Opcodes::OpFnegd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FNEGS", number: Opcodes::OpFnegs, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FNMACD", number: Opcodes::OpFnmacd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FNMACS", number: Opcodes::OpFnmacs, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FNMSCD", number: Opcodes::OpFnmscd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FNMSCS", number: Opcodes::OpFnmscs, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FNMULD", number: Opcodes::OpFnmuld, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FNMULS", number: Opcodes::OpFnmuls, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FSITOD", number: Opcodes::OpFsitod, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FSITOS", number: Opcodes::OpFsitos, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FSQRTD", number: Opcodes::OpFsqrtd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FSQRTS", number: Opcodes::OpFsqrts, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FSTD", number: Opcodes::OpFstd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FSTMIAD", number: Opcodes::OpFstmiad, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FSTMIAS", number: Opcodes::OpFstmias, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FSTMIAX", number: Opcodes::OpFstmiax, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FSTMDBD", number: Opcodes::OpFstmdbd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FSTMDBS", number: Opcodes::OpFstmdbs, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FSTMDBX", number: Opcodes::OpFstmdbx, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FSTS", number: Opcodes::OpFsts, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FSUBD", number: Opcodes::OpFsubd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FSUBS", number: Opcodes::OpFsubs, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FTOSID", number: Opcodes::OpFtosid, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FTOSIZD", number: Opcodes::OpFtosizd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FTOSIS", number: Opcodes::OpFtosis, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FTOSIZS", number: Opcodes::OpFtosizs, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FTOUID", number: Opcodes::OpFtouid, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FTOUIZD", number: Opcodes::OpFtouizd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FTOUIS", number: Opcodes::OpFtouis, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FTOUIZS", number: Opcodes::OpFtouizs, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FUITOD", number: Opcodes::OpFuitod, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "FUITOS", number: Opcodes::OpFuitos, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "LDC", number: Opcodes::OpLdc, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "LDC2", number: Opcodes::OpLdc2, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "LDM", number: Opcodes::OpLdm, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "LDR", number: Opcodes::OpLdr, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "MCR", number: Opcodes::OpMcr, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "MCR2", number: Opcodes::OpMcr2, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "MCRR", number: Opcodes::OpMcrr, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "MLA", number: Opcodes::OpMla, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "MOV", number: Opcodes::OpMov, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "MOVW", number: Opcodes::OpMovw, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "MRC", number: Opcodes::OpMrc, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "MRC2", number: Opcodes::OpMrc2, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "MRRC", number: Opcodes::OpMrrc, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "MRS", number: Opcodes::OpMrs, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "MSR", number: Opcodes::OpMsr, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "MUL", number: Opcodes::OpMul, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "MVN", number: Opcodes::OpMvn, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "ORR", number: Opcodes::OpOrr, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "PLD", number: Opcodes::OpPld, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "QADD", number: Opcodes::OpQadd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "QDADD", number: Opcodes::OpQdadd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "QDSUB", number: Opcodes::OpQdsub, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "QSUB", number: Opcodes::OpQsub, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "RSB", number: Opcodes::OpRsb, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "RSC", number: Opcodes::OpRsc, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "SBC", number: Opcodes::OpSbc, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "SMLABB", number: Opcodes::OpSmlabb, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "SMLABT", number: Opcodes::OpSmlabt, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "SMLATB", number: Opcodes::OpSmlatb, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "SMLATT", number: Opcodes::OpSmlatt, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "SMLAL", number: Opcodes::OpSmlal, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "SMLALBB", number: Opcodes::OpSmlalbb, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "SMLALBT", number: Opcodes::OpSmlalbt, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "SMLALTB", number: Opcodes::OpSmlaltb, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "SMLALTT", number: Opcodes::OpSmlaltt, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "SMLAWB", number: Opcodes::OpSmlawb, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "SMLAWT", number: Opcodes::OpSmlawt, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "SMULBB", number: Opcodes::OpSmulbb, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "SMULBT", number: Opcodes::OpSmulbt, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "SMULTB", number: Opcodes::OpSmultb, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "SMULTT", number: Opcodes::OpSmultt, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "SMULWB", number: Opcodes::OpSmulwb, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "SMULWT", number: Opcodes::OpSmulwt, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "SMULL", number: Opcodes::OpSmull, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "STC", number: Opcodes::OpStc, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "STC2", number: Opcodes::OpStc2, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "STM", number: Opcodes::OpStm, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "STR", number: Opcodes::OpStr, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "SUB", number: Opcodes::OpSub, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "SWI", number: Opcodes::OpSwi, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "SWP", number: Opcodes::OpSwp, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "TEQ", number: Opcodes::OpTeq, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "TST", number: Opcodes::OpSmlalbt, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "UMLAL", number: Opcodes::OpUmlal, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "UMULL", number: Opcodes::OpUmull, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "UDF", number: Opcodes::OpUdf, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "LSL", number: Opcodes::OpLsl, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "LSR", number: Opcodes::OpLsr, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "SEV", number: Opcodes::OpSev, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "DSB", number: Opcodes::OpDsb, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "LDREX", number: Opcodes::OpLdrex, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "STREX", number: Opcodes::OpStrex, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "ADR", number: Opcodes::OpAdr, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "LDREXB", number: Opcodes::OpLdrexb, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "STREXB", number: Opcodes::OpStrexb, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "DMB", number: Opcodes::OpDmb, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "CLREX", number: Opcodes::OpClrex, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "REV", number: Opcodes::OpRev, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "REV16", number: Opcodes::OpRev16, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "UXTH", number: Opcodes::OpUxth, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "WFE", number: Opcodes::OpWfe, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "WFI", number: Opcodes::OpWfi, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "ISB", number: Opcodes::OpIsb, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "VADD", number: Opcodes::OpVadd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "VADDL", number: Opcodes::OpVaddl, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "VADDW", number: Opcodes::OpVaddw, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "VMUL", number: Opcodes::OpVmul, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "VMULL", number: Opcodes::OpVmull, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "VMSR", number: Opcodes::OpVmsr, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "VMRS", number: Opcodes::OpVmrs, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "VLDR", number: Opcodes::OpVldr, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "VSTR", number: Opcodes::OpVstr, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "VDIV", number: Opcodes::OpVdiv, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "VMLA", number: Opcodes::OpVmla, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "VMLS", number: Opcodes::OpVmls, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "VMIN", number: Opcodes::OpVmin, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "VMAX", number: Opcodes::OpVmax, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "VSUB", number: Opcodes::OpVsub, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "VABS", number: Opcodes::OpVabs, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "VABD", number: Opcodes::OpVabd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "VLD1", number: Opcodes::OpVld1, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "VST1", number: Opcodes::OpVst1, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "VPADD", number: Opcodes::OpVpadd, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 },
    Mnemonic { name: "VMOV", number: Opcodes::OpVmov, first_instruction_format: Encoding::EncodingSignedImm24, last_instruction_format: Encoding::EncodingAddressingMode1 }
];
